### ISSUE TITLE
Race condition: BackgroundPlotter has no attribute named image

### ISSUE THREAD

**Issue by otvam** [pyvista/pyvistaqt#324]
When running the following code and pressing "q" to close the windows:

```python
import pyvista
import pyvistaqt
import qtpy.QtWidgets
import qtpy.QtGui
import time

app = qtpy.QtWidgets.QApplication([])

pl1 = pyvistaqt.BackgroundPlotter(menu_bar=False, toolbar=False, app=app)
pl1.add_mesh(pyvista.Sphere())

pl2 = pyvistaqt.BackgroundPlotter(menu_bar=False, toolbar=False, app=app)
pl2.add_mesh(pyvista.Sphere())

app.exec_()
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/ml/venv/lib/python3.10/site-packages/pyvista/plotting/plotting.py", line 1986, in key_press_event
    self.iren.key_press_event(*args, **kwargs)
  File "/home/ml/venv/lib/python3.10/site-packages/pyvista/plotting/render_window_interactor.py", line 303, in key_press_event
    func()
  File "/home/ml/venv/lib/python3.10/site-packages/pyvista/plotting/plotting.py", line 1938, in _prep_for_close
    self.last_image = self.screenshot(True, return_img=True)
  File "/home/ml/venv/lib/python3.10/site-packages/pyvista/plotting/plotting.py", line 5609, in screenshot
    return self._save_image(self.image, filename, return_img)
  File "/home/ml/venv/lib/python3.10/site-packages/pyvistaqt/rwi.py", line 426, in __getattr__
    raise AttributeError(self.__class__.__name__ +
AttributeError: BackgroundPlotter has no attribute named image
Aborted (core dumped)
```

These seems to be a race condition as adding `time.sleep(0.3)` after each `plotter.add_mesh` seems to solve the issue. I poke a bit around `pyvista/plotting.py` without being able to identify the problem.

Here is my configuration:

```
--------------------------------------------------------------------------------
  Date: Thu Mar 02 02:10:16 2023 EST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 7.7 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (KBL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 22.2.5

  Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

           pyvista : 0.38.3
               vtk : 9.2.6
             numpy : 1.24.2
           imageio : 2.26.0
            scooby : 0.7.1
             pooch : v1.7.0
        matplotlib : 3.7.0
         pyvistaqt : 0.9.1
             PyQt5 : 5.15.9
          colorcet : 3.0.1
           cmocean : 2.0
        ipyvtklink : 0.2.2
        ipywidgets : 8.0.4
             scipy : 1.10.1
              tqdm : 4.64.1
            meshio : 5.3.4
      nest_asyncio : 1.5.6
--------------------------------------------------------------------------------
```

**Comment by larsoner** [comment]
I think this is the same thing as https://github.com/pyvista/pyvistaqt/pull/317 / https://github.com/pyvista/pyvista/pull/4036

**Comment by larsoner** [comment]
@otvam can you see if latest `main` of pyvista fixes your issue?

**Comment by otvam** [comment]
Yes, the problem is solved with the latest git version.

This is also solving a related problem that used to appear when the `pyvistaqt.BackgroundPlotter` is created with `show=False`.

Many thanks for fixing this issue.
