### ISSUE TITLE
The BackgroundPlotter raised an QtDeprecationError on my system. What can I do to fix this?

### ISSUE THREAD

**Issue by RobertKoenig1337** [pyvista/pyvistaqt#35]
Hello all, 

I am working on a simulation of a machining process. Therefore I need to update the visualization permanently while the simulation is running. I want to use pyvista with the BackgroundPlotter for this task. I set up the library in my Anaconda Python 3 with PyCharm. I installed the pyvista package, numpy and pyvistaqt (and a few others). When I am trying to process the example given by PyVista for BackgroundPlotting I run into an error. (https://docs.pyvista.org/plotting/plotting.html#background-plotting)
I just started programming recently sorry if the reason is an obvious mistake. 

Traceback (most recent call last):
  File "C:/Abtragsimulation/Programm with Conda/test files/testing pv.py", line 14, in <module>
    plotter = pv.BackgroundPlotter()
  File "C:\Users\Robert\miniconda3\envs\Programm with Conda\lib\site-packages\pyvista\plotting\__init__.py", line 35, in __init__
    raise QtDeprecationError('BackgroundPlotter')
pyvista.plotting.QtDeprecationError: `BackgroundPlotter` has moved to pyvistaqt.
    You can install this from PyPI with: `pip install pyvistaqt`
    See https://github.com/pyvista/pyvistaqt

When I try installing pyvistaqt as the error suggests, the terminal prompts a list with all packages needed and says that the requirements are all already satisfied. 
[Requirements already satisfied.txt](https://github.com/pyvista/pyvistaqt/files/4903247/Requirements.already.satisfied.txt)

How can I fix the problem? Is this even the right way to visualize a model that is changing all the time while the simulation is running? 

Python CODE: 
[Backgroundplotter error.txt](https://github.com/pyvista/pyvistaqt/files/4903223/Backgroundplotter.error.txt)

Thank you very much in advance.

**Comment by banesullivan** [comment]
Perhaps our error message `'BackgroundPlotter' has moved to pyvistaqt.` is unclear. By "moved to pyvistaqt.", we really mean moved - completely. The `BackgroundPlotter` class is no longer accesible from `pyvista` but from `pyvistaqt` now. Thus, in your code, you must replace:

```py
import pyvista as pv
....

plotter = pv.BackgroundPlotter()
```

with

```py
import pyvista as pv
from pyvistaqt import BackgroundPlotter
....

plotter = BackgroundPlotter()
```

@pyvista/developers, I've been hearing a lot of confusion over this error message. Can you think of a clearer way to state this in the actual error that is raised

**Comment by banesullivan** [comment]
Perhaps we should change it to:

```
pyvista.plotting.QtDeprecationError: `BackgroundPlotter` has moved to pyvistaqt.
    You can install this from PyPI with: `pip install pyvistaqt`
    Then import it via:
        from pyvistaqt import BackgroundPlotter
    `BackgroundPlotter` is no longer accessible from `pyvista.BackgroundPlotter`
    See https://github.com/pyvista/pyvistaqt
```

**Comment by banesullivan** [comment]
Moving over to PyVista, so that we can improve this error message there
