### ISSUE TITLE
BUG: conda

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvistaqt#99]
Some failures have been detected for the `conda` jobs. Those use `PySide2` by default and the error seems to be related to Qt/QtPy:

```
Installing collected packages: pyvistaqt
  Running setup.py develop for pyvistaqt
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/share/miniconda/envs/pyvistaqt-env/include/python3.8/UNKNOWN
sysconfig: /usr/share/miniconda/envs/pyvistaqt-env/include/python3.8
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Successfully installed pyvistaqt-0.4.dev0
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/pyvista/utilities/errors.py", line 232, in __init__
    scooby.Report.__init__(self, additional=additional, core=core,
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/scooby/report.py", line 170, in __init__
    PythonInfo.__init__(self, additional=additional, core=core,
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/scooby/report.py", line 84, in __init__
    self._add_packages(optional, optional=True)  # Optional packages
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/scooby/report.py", line 99, in _add_packages
    name, version = get_version(pckg)
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/scooby/report.py", line 377, in get_version
    module = importlib.import_module(name)
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/pyvistaqt/pyvistaqt/pyvistaqt/__init__.py", line 3, in <module>
    from pyvistaqt.plotting import BackgroundPlotter, MainWindow, MultiPlotter, QtInteractor
  File "/home/runner/work/pyvistaqt/pyvistaqt/pyvistaqt/plotting.py", line 57, in <module>
    from qtpy import QtCore
  File "/usr/share/miniconda/envs/pyvistaqt-env/lib/python3.8/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by GuillaumeFavelier** [comment]
It seems that installing `vtk` through `conda` now introduces a dependency to `qt` somehow. Is it something recent? I don't understand why this is necessary. But I believe this need to be addressed to order to have a clean env for `PySide`.
